# Generated by Django 5.0.1 on 2024-01-23 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hwapp.thing'),
        ),
    ]
